#!/bin/bash
echo Of which computers would you like to check the status from rpi01 to rpi18? Separate them with a space.
echo If you want to check them all leave this blank.
read complist

if [ -z "$complist" ]
then
	complist="rpi01 rpi02 rpi03 rpi04 rpi05 rpi06 rpi07 rpi08 rpi09 rpi10 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpi18"
fi

for comp in $complist
do 
ping -c 1 -W 1 "$comp" &> /dev/null
	if [ $? -eq 0 ]
	then
		echo "$comp : alive"
	else
		echo "$comp : dead"
	fi 
done
